import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.scss";

const AkzidenzGroteskBQ = localFont({
  display: "swap",
  variable: "--font-overused-grotesk",
  src: [
    {
      path: "../public/fonts/AkzidenzGroteskBQ-Cnd.ttf",
      weight: "400",
      style: "regular",
    },
    {
      path: "../public/fonts/AkzidenzGroteskBQ-MdCnd.ttf",
      weight: "500",
      style: "medium",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={AkzidenzGroteskBQ.className}>{children}</body>
    </html>
  );
}
